name: Deploy Home Assistant

on:
  push:

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Snapshot VM
        run: |
          ssh gitops@${{ secrets.PROXMOX_HOST }} \
          "/usr/sbin/qm snapshot ${{ secrets.PROXMOX_VM_ID }} pre-gitops-$(date +%s)"
          
