name: Deploy Home Assistant

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Snapshot VM
        run: |
          SNAP="gitops-$(date +%s)"
          echo "SNAP_NAME=$SNAP" >> $GITHUB_ENV
          
          curl -k -v -X POST \
          "https://${{ secrets.PROXMOX_HOST }}:8006/api2/json/nodes/proxmox/qemu/${{ secrets.PROXMOX_VM_ID }}/snapshot" \
          -H 'Authorization: PVEAPIToken=${{ secrets.PROXMOX_TOKEN_ID }}=${{ secrets.PROXMOX_TOKEN_SECRET }}' \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "snapname=$SNAP"
  
      - name: Trigger Home Assistant
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.HA_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"event_type":"github_pull_config"}' \
            https://${{ secrets.HA_URL }}/api/events/github_pull_config

      - name: Restart Home Assistant
        run: |
          echo "Restarting Home Assistant..."
      
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.HA_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://${{ secrets.HA_URL }}/api/services/homeassistant/restart
      
      - name: Detect restart and verify Home Assistant startup
        id: healthcheck
        continue-on-error: true
        run: |
          echo "Detecting Home Assistant restart..."
      
          HA_URL="https://${{ secrets.HA_URL }}"
          TOKEN="${{ secrets.HA_TOKEN }}"
      
          MAX_RETRIES=120
          SLEEP_TIME=5
      
          went_down=false
          came_back=false
      
          for i in $(seq 1 $MAX_RETRIES); do
            STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: Bearer $TOKEN" \
              $HA_URL/api/ || echo "000")
      
            echo "Attempt $i/$MAX_RETRIES - API status: $STATUS"
      
            if [ "$STATUS" != "200" ]; then
              echo "Home Assistant is restarting..."
              went_down=true
            fi
      
            if [ "$went_down" = true ] && [ "$STATUS" = "200" ]; then
              echo "Home Assistant API back online"
      
              STATES_STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" \
                -H "Authorization: Bearer $TOKEN" \
                $HA_URL/api/states)
      
              if [ "$STATES_STATUS" = "200" ]; then
                echo "Home Assistant fully operational"
                came_back=true
                break
              fi
            fi
      
            sleep $SLEEP_TIME
          done
      
          if [ "$came_back" != true ]; then
            echo "Home Assistant failed to start correctly"
            exit 1
          fi
      
      - name: Show Home Assistant error logs
        if: steps.healthcheck.outcome == 'failure'
        run: |
          echo "Fetching Home Assistant error logs..."
      
          curl -s \
            -H "Authorization: Bearer ${{ secrets.HA_TOKEN }}" \
            https://${{ secrets.HA_URL }}/api/error_log
          
      - name: Rollback VM snapshot
        if: steps.healthcheck.outcome == 'failure'
        run: |
          echo "Health check failed — rolling back VM"
      
          #curl -k -X POST \
          #"https://${{ secrets.PROXMOX_HOST }}:8006/api2/json/nodes/proxmox/qemu/${{ secrets.PROXMOX_VM_ID }}/snapshot/${{ env.SNAP_NAME }}/rollback" \
          #-H "Authorization: PVEAPIToken=${{ secrets.PROXMOX_TOKEN_ID }}=${{ secrets.PROXMOX_TOKEN_SECRET }}"
